global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: rssant_api
    metrics_path: "/admin/metrics"
    static_configs:
      - targets: ["192.168.0.102:6788"]
  - job_name: actorlib_example_fab
    static_configs:
      - targets: ["192.168.0.102:8088"]
  - job_name: rssant_worker
    static_configs:
      - targets: ["192.168.0.102:6792"]
  - job_name: rssant_harbor
    static_configs:
      - targets: ["192.168.0.102:6791"]
  - job_name: rssant_scheduler
    static_configs:
      - targets: ["192.168.0.102:6790"]
